### ISSUE TITLE
"izolacja" eksponatu po kliknęciu

### ISSUE THREAD

**Issue by topolskib** [flaminka/RiBigDataProjekt1#10]
Klikniecie na eksponat "izoluje" je - pokazywane są tylko ścieżki z niego

**Comment by flaminka** [comment]
Trzeba by może w tej obecnej zakładce z mapą, pod menu dać jakby dodatkowe okienko do tego:

kliknięcie na eksponat da nam jak do tej pory nazwę urządzenia, dodatkowo top 5 najczęstszych urządzeń po odwiedzeniu tego (procentowo)

+ kliknięcie da nam histogram tego urządzenia dla danych filtrów z czasami urządzeń

+ jakieś inne statystyki? czego? jakie?

+ tak jak w komentarzu Bartka, pokazać tylko ścieżki od niego (może właśnie nad tymi ścieżkami dodać etykiety dla top 5, zamiast tabelki )

+ żeby po wyizolowaniu tego obiektu, ścieżka typowa właśnie od niego startowała
